### ISSUE TITLE
Fail to release to pypi and conda-forge

### ISSUE THREAD

**Issue by pedrovma** [pysal/spreg#51]
I am still not able to automatically upload the release to pypi and conda-forge. I did try to follow the instructions at https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ . Spreg has the pypi API token attached as a Secret, but it did not upload. Help, please? Many thanks!

**Comment by knaaptime** [comment]
i think we just need to update the recipe a bit because some of the conventions were deprecated. We just updated the one from [tobler](https://github.com/pysal/tobler/blob/master/.github/workflows/upload_package.yml) that can serve as a model here. 

I can do a PR probably this evening

**Comment by jGaboardi** [comment]
@pedrovma Did you push a [tagged commit](https://git-scm.com/book/en/v2/Git-Basics-Tagging) ***directly*** to the `master` branch with the following pattern: `'v*'` i.e. `v2.0` or `v5.4.3`?

**Comment by pedrovma** [comment]
> @pedrovma Did you push a [tagged commit](https://git-scm.com/book/en/v2/Git-Basics-Tagging) _**directly**_ to the `master` branch with the following pattern: `'v*'` i.e. `v2.0` or `v5.4.3`?

Yep. The push triggered the new release update to GH and DOI, but PyPI and conda-forge stalled.

**Comment by knaaptime** [comment]
the [failures](https://github.com/pysal/spreg/actions/runs/453384073) are complaining about the way we set the environment variables (which is what we fixed in the new version of the recipe) so we should have this fixed in short order

**Comment by jGaboardi** [comment]
Addressing in #52

**Comment by pedrovma** [comment]
Should I make a new post release?

**Comment by jGaboardi** [comment]
yes

**Comment by jGaboardi** [comment]
@pedrovma Would you like me to work on automated doc builds for `spreg`? @knaaptime made a great solution for a GHA+GH-pages that I can implement here. See examples for [`tobler`](https://github.com/pysal/tobler/blob/master/.github/workflows/build_docs.yml) and [`spaghetti`](https://github.com/pysal/spaghetti/blob/main/.github/workflows/build_docs.yml).

**Comment by pedrovma** [comment]
Sure. It would be awesome. Many thanks!

**Comment by jGaboardi** [comment]
OK, hold off on the new release until I get that squared away.

**Comment by pedrovma** [comment]
Ok. I had tried it already but it failed anyway. =)
So I'll hold for another attempt. Thanks!

**Comment by jGaboardi** [comment]
> Ok. I had tried it already but I made a mistake and it failed anyway. =)
> So I'll hold for another attempt. Thanks!

This is no good... What exact error are you getting?

**Comment by pedrovma** [comment]
Release and publish error: https://github.com/pysal/spreg/actions/runs/454350432
Doc build error: https://github.com/pysal/spreg/actions/runs/454343231

**Comment by jGaboardi** [comment]
**Resolved**
* [ ] Release and publish error (https://github.com/pysal/spreg/actions/runs/454350432)
  * This appears to be an error with not using [environment files](https://github.com/pysal/spaghetti/tree/main/ci), the best way forward (IMHO) is to migrate to GHA for testing through env `.yml` files. I can set this up if you would like (and also migrate to `codecov` from `coveralls` to conform with other PySAL submodules).
* [ ] Doc build error

**Comment by pedrovma** [comment]
It would be great if you could do this, @jGaboardi . Thank you so much!

**Comment by jGaboardi** [comment]
@pedrovma Following #64, the release workflow should be functional. Try triggering that when you get a chance.

**Comment by pedrovma** [comment]
Awesome work, many thanks @jGaboardi !
It seems there is still an error in the process that uploads the release to Pypi:
https://github.com/pysal/spreg/actions/runs/466296639

**Comment by jGaboardi** [comment]
argh... OK, I will give this some attention later today unless @knaaptime
has time to look at it before then. It is probably a small typo or careless
oversight of mine.

**Comment by jGaboardi** [comment]
@pedrovma I made an error in `setup.py`. I fix that directly on `master` then we can try to release action again.

**Comment by jGaboardi** [comment]
@pedrovma Shall I try the updated release action or would you like to?

**Comment by jGaboardi** [comment]
@knaaptime @pedrovma I'll go ahead and cut the release later today unless there are any objections.

**Comment by jGaboardi** [comment]
release+publish action is now fully functional --> [`v1.2.2`](https://github.com/pysal/spreg/releases/tag/v1.2.2)
